name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node # Multiple release types are supported
          default-branch: main
          changelog-types: '[{"type": "chore","section": "Others","hidden": false},{"type": "feat","section": "Features","hidden": false},{"type": "fix","section": "Bug Fixes","hidden": false},{"type": "docs","section": "Docs","hidden": false},{"type": "style","section": "Styling","hidden": false},{"type": "refactor","section": "Code Refactoring","hidden": false},{"type": "config","section": "Configuration","hidden": false},{"type": "remove","section": "Remove","hidden": false},{"type": "deploy","section": "Deploy System","hidden": false}]'
